// <auto-generated />
using System;
using FlatFileGenerator.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlatFileGenerator.Web.Migrations
{
    [DbContext(typeof(FlatFileContext))]
    [Migration("20251219131858_PolicyNumber")]
    partial class PolicyNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlatFileGenerator.Core.Models.InputFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("HashCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("InputFiles");
                });

            modelBuilder.Entity("FlatFileGenerator.Core.Models.Logs.LogModels.LogModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("Date");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("FlatFileGenerator.Core.Models.ReceiptDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContributionRateFromDate")
                        .HasColumnType("Date");

                    b.Property<string>("Cpr")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cvr")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("DeviationCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeviationEndDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("DeviationStartDate")
                        .HasColumnType("Date");

                    b.Property<decimal?>("EmployeeSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EmployeeSalaryStartDate")
                        .HasColumnType("Date");

                    b.Property<decimal?>("EmployerContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmployerContributionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EmploymentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EmploymentRateStartDate")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("EmploymentTerminationDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("Date");

                    b.Property<string>("LaborAgreementNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NormalContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NormalContributionStartDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("Date");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("PersonFullName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int?>("PolicyNumber")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("Date");

                    b.Property<int?>("TermsOfSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("Date");

                    b.Property<decimal?>("TotalContributionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReceiptDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
